/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.catvod.demo;

import java.util.ArrayList;
import java.util.List;

import com.github.catvod.crawler.Spider;
import com.github.catvod.spider.HOME;
import com.github.catvod.spider.TX;

import org.json.JSONArray;
import org.json.JSONObject;

public class MainActivity {
    public static void main(String[] args) {
        // TX spider = new TX();
        HOME spider = new HOME();
        JSONArray res_home = test_home(spider);
        // res_home.getString(0)测试是电视剧还是电影...，可以根据index来切换
        List<String> res_category = test_category(spider, res_home.getString(0));
        // res_category.get(1)测试是那一部视频...，可以根据index来切换
        test_detail(spider, res_category.get(1));
        test_player(spider);
    }

    public static JSONArray test_home(Spider spider) {
        // 标题栏
        JSONArray res = new JSONArray();
        System.out.println("==========homeContent:=======\n");
        String strhomeContent = spider.homeContent(true);
        JSONObject result = new JSONObject(new String(strhomeContent));
        try {
            JSONArray classes = result.getJSONArray("class");
            try {
                for (int i = 0; i < classes.length(); i++) {
                    System.out.print(classes.getJSONObject(i).get("type_name") + "["
                            + classes.getJSONObject(i).get("type_id") + "]" + "  ");
                    res.put(classes.getJSONObject(i).get("type_id"));
                }
                System.out.println();
            } catch (Exception e) {
                System.out.println("未读取到type_name或者type_id，请检查json格式！");
            }
        } catch (Exception e) {
            System.out.println("未读取到class，请检查json格式！");
        }
        return res;
    }

    public static List<String> test_category(Spider spider, String tid) {
        List<String> res = new ArrayList<>();
        // 标题栏下的视频内容
        System.out.println("\r\n==========categoryContent:=======\r\n");
        String strcategoryContent = spider.categoryContent(tid, "1", true, null);
        JSONObject result = new JSONObject(new String(strcategoryContent));
        try {
            String page = result.getString("page");
            System.out.println("//当前页");
            System.out.println("page:" + page);
        } catch (Exception e) {
            System.out.println("//当前页");
            System.out.println("没有解析到page，请检查！！！");
        }
        try {
            int pagecount = result.getInt("pagecount");
            System.out.println("// 总共几页");
            System.out.println("pagecount:" + pagecount);
        } catch (Exception e) {
            System.out.println("// 总共几页");
            System.out.println("没有解析到pagecount，请检查！！！");
        }
        try {
            int limit = result.getInt("limit");
            System.out.println("// 每页几条数据");
            System.out.println("limit:" + limit);
        } catch (Exception e) {
            System.out.println("// 每页几条数据");
            System.out.println("没有解析到limit，请检查！！！");
        }
        try {
            int total = result.getInt("total");
            System.out.println(" // 总共多少调数据");
            System.out.println("total:" + total);
        } catch (Exception e) {
            System.out.println(" // 总共多少调数据");
            System.out.println("没有解析到total，请检查！！！");
        }
        try {
            JSONArray list = result.getJSONArray("list");
            System.out.println(" //视频列表");
            try {
                for (int i = 0; i < list.length(); i++) {
                    System.out.print(list.getJSONObject(i).get("vod_name") + "["
                            + list.getJSONObject(i).get("vod_id") + "]" + "\r\n");
                    res.add(list.getJSONObject(i).get("vod_id").toString());
                }
            } catch (Exception e) {
                System.out.println("视频列表解析出现问题，请检查json格式!");
            }
        } catch (Exception e) {
            System.out.println(" // 总共多少调数据");
            System.out.println("没有解析到list，请检查！！！");
        }

        return res;

    }

    public static String test_detail(Spider spider, String ids0) {
        // 视频详细信息,注意List<String> ids只有一个tid
        List<String> ids = new ArrayList<>();
        ids.add(ids0);
        System.out.println("\r\n==========detailContent:=======\r\n");
        String strdetailContent = spider.detailContent(ids);
        JSONObject result = new JSONObject(new String(strdetailContent));
        try {
            JSONArray list = result.getJSONArray("list");
            try {
                ArrayList<String> sources = new ArrayList<>();
               String vod_play_from =list.getJSONObject(0).getString("vod_play_from");
               System.out.println(vod_play_from);
            } catch (Exception e) {
                // TODO: handle exception
            }

            //System.out.println(list);
        } catch (Exception e) {
            System.out.println("未读取到list,请检查json格式!!");
        }

        return "";

    }

    public static String test_player(Spider spider) {
        // 播放内容
        System.out.println("\r\n==========playerContent=======\r\n");
        String strplayerContent = spider.playerContent("",
                "http://localhost:8080/%E5%B0%91%E5%84%BF/%E6%B1%AA%E6%B1%AA%E9%98%9F%E5%90%88%E9%9B%86/%E7%AC%AC8%E5%AD%A31080p/%E6%B1%AA%E6%B1%AA%E9%98%9F%E7%AB%8B%E5%A4%A7%E5%8A%9F.%E7%AC%AC%E5%85%AB%E5%AD%A3.1080P.%E7%AC%AC10%E9%9B%86.mp4",
                null);
        System.out.println(strplayerContent);

        return "";
    }
}
