name: Update Commit

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v1
      - name: Clone auto
        run: |

          git clone https://asters1:${{secrets.USER_TOKEN}}@github.com/asters1/auto
          cd auto
          oldcommit=$(./jq ./tvjar/tvjarCommit.json new)
          newcommit=$(curl -sL https://github.com/asters1/test/commits/asters1/tvjar_test |grep -o "/asters1/tvjar_test/commit/[a-z0-9]\+" |head -1 | cut -d\/ -f5)
          echo $oldcommit
          echo $newcommit



