name: Update Tvjar

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v1
      - name: Clone auto
        run: |
          git clone https://asters1:${{secrets.USER_TOKEN}}@github.com/asters1/auto
          cd auto
          ls


